Data Scraping For Monetary Policy Project --> As per Suggestion on Document I have been given the United Kingdom - Inflation CPI - Funds rate - Frequency = Quarterly

## Packages

In [39]:
import pandas as pd
import requests
import numpy as np

### Prices, CPI

In [40]:
# Getting Data from Fred

API_KEY = "51286e2abae242cda74d0d166f50b652"
SERIES_ID_CPI = "CPALTT01GBQ657N"

url = "https://api.stlouisfed.org/fred/series/observations"

parameters = {
    "series_id": SERIES_ID_CPI,
    "api_key": API_KEY,
    "file_type": "json",
    "observation_start": "1955-04-01",
    "observation_end": "2023-10-01"
}
response = requests.get(url, params=parameters)
response.raise_for_status()
data_fred_CPI = response.json()
# making the observations into a dataframe
quarterly_cpi_unitedkingdom_fred_data_raw_df = pd.DataFrame(data_fred_CPI["observations"])
quarterly_cpi_unitedkingdom_fred_data_df = quarterly_cpi_unitedkingdom_fred_data_raw_df[["date", "value"]]
quarterly_cpi_unitedkingdom_fred_data_df["date"] = pd.to_datetime(quarterly_cpi_unitedkingdom_fred_data_df["date"])
quarterly_cpi_unitedkingdom_fred_data_df["value"] = pd.to_numeric(quarterly_cpi_unitedkingdom_fred_data_df["value"], errors="coerce")
quarterly_cpi_unitedkingdom_fred_data_df = quarterly_cpi_unitedkingdom_fred_data_df.set_index("date")
quarterly_cpi_unitedkingdom_fred_data_df.index = pd.PeriodIndex(quarterly_cpi_unitedkingdom_fred_data_df.index, freq="Q")

# Renaming the columns in my data frame so that they remain consistent when I have to go on and merge them 
quarterly_cpi_unitedkingdom_fred_data_df = quarterly_cpi_unitedkingdom_fred_data_df.rename(columns= {'value':'CPI'})

# transfomring it into log levels to mimic Inflation growth as per the slides

quarterly_cpi_unitedkingdom_fred_data_df["CPI Log Growth Rate"] = np.log(quarterly_cpi_unitedkingdom_fred_data_df["CPI"]).diff()


quarterly_cpi_unitedkingdom_fred_data_df.head()

/var/folders/k1/mhyzg0w15gb04d0x6q7gdp2w0000gn/T/ipykernel_9285/3321165595.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quarterly_cpi_unitedkingdom_fred_data_df["date"] = pd.to_datetime(quarterly_cpi_unitedkingdom_fred_data_df["date"])
/var/folders/k1/mhyzg0w15gb04d0x6q7gdp2w0000gn/T/ipykernel_9285/3321165595.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quarterly_cpi_unitedkingdom_fred_data_df["value"] = pd.to_numeric(quarterly_cpi_unitedkingdom_fred_data_df["value"], errors="coerce")
/opt/anaconda3/lib/python3.13/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/opt/anaconda3/lib/python3.13/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

             CPI  CPI Log Growth Rate
date
1955Q2  1.119177                  NaN
1955Q3  1.405923             0.228100
1955Q4  2.300885             0.492600
1956Q1  0.607093            -1.332366
1956Q2  2.090939             1.236686

GDP Deflator

In [41]:
# GDP Deflator - Fred Data Base 

SERIES_ID_GDP_DEFLATE = "NGDPDSAIXGBQ"

parameters = {
    "series_id": SERIES_ID_GDP_DEFLATE,
    "api_key": API_KEY,
    "file_type": "json",
    "observation_start": "1955-04-01",
    "observation_end": "2026-01-01"
}

response = requests.get(url, params=parameters)
response.raise_for_status()
data_fred_GDP_Deflator = response.json()


quarterly_gdp_deflator_data_raw_df = pd.DataFrame(data_fred_GDP_Deflator["observations"])
quarterly_gdp_deflator_data_df = quarterly_gdp_deflator_data_raw_df[["date","value"]]
quarterly_gdp_deflator_data_df["date"] = pd.to_datetime(quarterly_gdp_deflator_data_df["date"])
quarterly_gdp_deflator_data_df["value"] = pd.to_numeric(quarterly_gdp_deflator_data_df["value"], errors="coerce")
quarterly_gdp_deflator_data_df = quarterly_gdp_deflator_data_df.set_index("date")
quarterly_gdp_deflator_data_df.index = pd.PeriodIndex(quarterly_gdp_deflator_data_df.index, freq="Q")

# Transforming into log levels to mimic inflation

quarterly_gdp_deflator_data_df["GDP Deflator_logged"] = np.log(quarterly_gdp_deflator_data_df["value"])
quarterly_gdp_deflator_data_df["GDP Deflators CPI Proxy"] = quarterly_gdp_deflator_data_df["GDP Deflator_logged"].diff()

quarterly_gdp_deflator_data_df = quarterly_gdp_deflator_data_df[["GDP Deflator_logged", "GDP Deflators CPI Proxy"]].dropna()

quarterly_gdp_deflator_data_df.head()

/var/folders/k1/mhyzg0w15gb04d0x6q7gdp2w0000gn/T/ipykernel_9285/269056796.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quarterly_gdp_deflator_data_df["date"] = pd.to_datetime(quarterly_gdp_deflator_data_df["date"])
/var/folders/k1/mhyzg0w15gb04d0x6q7gdp2w0000gn/T/ipykernel_9285/269056796.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quarterly_gdp_deflator_data_df["value"] = pd.to_numeric(quarterly_gdp_deflator_data_df["value"], errors="coerce")

        GDP Deflator_logged  GDP Deflators CPI Proxy
date
1955Q3             1.520057                 0.016863
1955Q4             1.544279                 0.024221
1956Q1             1.559656                 0.015377
1956Q2             1.574166                 0.014510
1956Q3             1.590796                 0.016631

Real activity and output

Real GDP

In [42]:
# Real GDP - Fred Data Base 

SERIES_ID_REAL_GDP = "NGDPRSAXDCGBQ" 

parameters = {
    "series_id": SERIES_ID_REAL_GDP,
    "api_key": API_KEY,
    "file_type": "json",
    "observation_start": "1955-04-01",
    "observation_end": "2025-01-01"
}

response = requests.get(url, params=parameters)
response.raise_for_status()
data_fred_real_gdp = response.json()

quarterly_uk_real_gdp_df = pd.DataFrame(data_fred_real_gdp["observations"])[["date", "value"]]
quarterly_uk_real_gdp_df["date"] = pd.to_datetime(quarterly_uk_real_gdp_df["date"])
quarterly_uk_real_gdp_df["value"] = pd.to_numeric(quarterly_uk_real_gdp_df["value"], errors="coerce")
# Rename
quarterly_uk_real_gdp_df = quarterly_uk_real_gdp_df.rename(columns={"value": "RealGDP"})

# setting the date as the index 
quarterly_uk_real_gdp_df = quarterly_uk_real_gdp_df.set_index("date")
quarterly_uk_real_gdp_df.index = pd.PeriodIndex(quarterly_uk_real_gdp_df.index, freq='Q')

quarterly_uk_real_gdp_df["RealGDP_Log"] = np.log(quarterly_uk_real_gdp_df["RealGDP"])
quarterly_uk_real_gdp_df["RealGDP_Log_Change"] = quarterly_uk_real_gdp_df["RealGDP_Log"].diff()

quarterly_uk_real_gdp_df.head()

         RealGDP  RealGDP_Log  RealGDP_Log_Change
date
1955Q2  145551.0    11.888282                 NaN
1955Q3  147995.0    11.904934            0.016652
1955Q4  147119.0    11.898997           -0.005937
1956Q1  148955.0    11.911400            0.012402
1956Q2  148835.0    11.910594           -0.000806

Policy Rate

In [43]:
SERIES_ID_POLICY_RATE = "BOERUKM" 
parameters = {
    "series_id": SERIES_ID_POLICY_RATE,
    "api_key": API_KEY,
    "file_type": "json",
    "observation_start": "1955-04-01",
    "observation_end": "2025-01-01"
}
response = requests.get(url, params=parameters)
response.raise_for_status()
data_fred_policy_rate = response.json()

monthly_uk_policy_rate_df = pd.DataFrame(data_fred_policy_rate["observations"])[["date", "value"]].copy()
monthly_uk_policy_rate_df["date"] = pd.to_datetime(monthly_uk_policy_rate_df["date"])
monthly_uk_policy_rate_df["value"] = pd.to_numeric(monthly_uk_policy_rate_df["value"], errors="coerce")
monthly_uk_policy_rate_df = monthly_uk_policy_rate_df.rename(columns={"value": "PolicyRate"})
monthly_uk_policy_rate_df = monthly_uk_policy_rate_df.set_index("date")
quarterly_uk_policy_rate_df = monthly_uk_policy_rate_df.resample("Q").mean()
quarterly_uk_policy_rate_df.index = quarterly_uk_policy_rate_df.index.to_period("Q") 
quarterly_uk_policy_rate_df["PolicyRate_Change"] = quarterly_uk_policy_rate_df["PolicyRate"].diff()

quarterly_uk_policy_rate_df.head()

/var/folders/k1/mhyzg0w15gb04d0x6q7gdp2w0000gn/T/ipykernel_9285/1350070602.py:18: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  quarterly_uk_policy_rate_df = monthly_uk_policy_rate_df.resample("Q").mean()

        PolicyRate  PolicyRate_Change
date
1955Q2    4.500000                NaN
1955Q3    4.500000           0.000000
1955Q4    4.500000           0.000000
1956Q1    5.166667           0.666667
1956Q2    5.500000           0.333333

3-month interest rate, United Kingdom & Growth Rate

In [44]:
SERIES_ID_SHORT = "IR3TTS01GBM156N"
params = {
    "series_id": SERIES_ID_SHORT,
    "api_key": API_KEY,
    "file_type": "json",
    "observation_start": "1955-04-01",
    "observation_end": "2025-01-01"
}
response = requests.get(url, params=params)
response.raise_for_status()
data_fred_short = response.json()

monthly_uk_short_rate_df = pd.DataFrame(data_fred_short["observations"])[["date", "value"]].copy()
monthly_uk_short_rate_df["date"] = pd.to_datetime(monthly_uk_short_rate_df["date"])
monthly_uk_short_rate_df["value"] = pd.to_numeric(monthly_uk_short_rate_df["value"], errors="coerce")
monthly_uk_short_rate_df = monthly_uk_short_rate_df.rename(columns={"value": "ShortRate"})
monthly_uk_short_rate_df = monthly_uk_short_rate_df.set_index("date")

quarterly_uk_short_rate_df = monthly_uk_short_rate_df.resample("Q").mean()
quarterly_uk_short_rate_df.index = quarterly_uk_short_rate_df.index.to_period("Q") 
quarterly_uk_short_rate_df["ShortRate_Change"] = quarterly_uk_short_rate_df["ShortRate"].diff()

quarterly_uk_short_rate_df.head()

/var/folders/k1/mhyzg0w15gb04d0x6q7gdp2w0000gn/T/ipykernel_9285/580450449.py:19: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  quarterly_uk_short_rate_df = monthly_uk_short_rate_df.resample("Q").mean()

        ShortRate  ShortRate_Change
date
1955Q2        NaN               NaN
1955Q3        NaN               NaN
1955Q4        NaN               NaN
1956Q1        NaN               NaN
1956Q2        NaN               NaN

Merging All the dataframes into one big final data frame

In [45]:
final_df = (
    quarterly_uk_short_rate_df.join(quarterly_uk_policy_rate_df, how="inner")
    .join(quarterly_uk_real_gdp_df, how='inner')
    .join(quarterly_gdp_deflator_data_df, how='inner')
    .join(quarterly_cpi_unitedkingdom_fred_data_df, how = 'inner')
    .loc["1960Q2": "2017Q1"]
)

final_df

,ShortRate,ShortRate_Change,PolicyRate,PolicyRate_Change,RealGDP,RealGDP_Log,RealGDP_Log_Change,GDP Deflator_logged,GDP Deflators CPI Proxy,CPI,CPI Log Growth Rate
date,,,,,,,,,,,
1960Q2,4.963333,0.393333,5.333333,0.333333,168948.0,12.037346,-0.006919,1.677209,0.016328,0.606980,2.995429
1960Q3,5.570000,0.606667,6.000000,0.666667,171442.0,12.052000,0.014654,1.676828,-0.000382,0.150830,-1.392346
1960Q4,4.693333,-0.876667,5.333333,-0.666667,172382.0,12.057468,0.005468,1.691078,0.014250,1.054217,1.944403
1961Q1,4.353333,-0.340000,5.000000,-0.333333,175276.0,12.074117,0.016649,1.699609,0.008531,0.536513,-0.675463
1961Q2,4.463333,0.110000,5.000000,0.000000,175974.0,12.078092,0.003974,1.695512,-0.004097,1.245182,0.841947
...,...,...,...,...,...,...,...,...,...,...,...
2016Q1,0.469233,-0.002367,0.500000,0.000000,625099.0,13.345665,0.005021,4.693441,0.005555,-0.298805,NaN
2016Q2,0.423133,-0.046100,0.500000,0.000000,629697.0,13.352994,0.007329,4.696005,0.002564,0.699301,NaN
2016Q3,0.249200,-0.173933,0.333333,-0.166667,632477.0,13.357399,0.004405,4.706035,0.010030,0.396825,-0.566584
2016Q4,0.097133,-0.152067,0.250000,-0.083333,636392.0,13.363570,0.006171,4.713067,0.007031,0.691700,0.555655
2017Q1,0.086900,-0.010233,0.250000,0.000000,642463.0,13.373065,0.009495,4.717171,0.004104,0.392542,-0.566509

In [47]:
final_df.to_csv("final_df.csv")